# Template project: https://gitlab.com/pages/jekyll
# Docs: https://docs.gitlab.com/ce/pages/
image: ruby:2.2.9

variables:
  JEKYLL_ENV: production
  BUNDLE_PATH: vendor/bundle

.before_script_bundle: &before_script_bundle
  - bundle install --deployment

test:
  stage: test
  before_script: *before_script_bundle
  script:
    - .ci/fast_build.sh
  cache:
    paths:
      - vendor
      - _site
  except:
    - master

check_code:
  stage: test
  image: coala/base
  script:
    - coala --ci
  except:
    - master

pages:
  stage: deploy
  before_script: *before_script_bundle
  script:
    - bundle exec jekyll build -d public
  cache:
    paths:
      - vendor
  artifacts:
    paths:
      - public
  only:
    - master
