---
title: Cipta Media
timezone: Asia/Jakarta
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
  juri-cme:
    title: Juri
    output: true
  hibahcme:
    title: Hibah CME
    output: true
  panitia:
    title: Panitia
    output: true
  laporan-keuangan-cms:
    title: Laporan Keuangan CMS
    output: true
description: Halaman pembuka Cipta Media Ekspresi, Perayaan pengetahuan dan kreatifitas ekspresi perempuan dalam aneka ragam bentuk dan dinamikanya dengan rupa hibah dana tunai.
keywords: Seni, Budaya, Perempuan, Karya, Hibah, Ford Foundation
disqus:
  name: ciptamedia-org
  noscript: Harap aktifkan Javascript untuk melihat dan memberi komentar
ga:
  id: UA-110953836-1
encoding: utf-8
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
baseurl: ""
defaults:
  -
    values:
      layout: "post"
  - scope:
      path: ''
      type: juri-cme
    values:
      layout: people
  - scope:
      path: ''
      type: panitia
    values:
      layout: panitia
  - scope:
      path: ''
      type: hibahcme
    values:
      layout: hibahcme
include:
  - _redirects
exclude:
  - README.md
  - LICENSE
  - static/img/members/README.md
  - vendor
