---
title: Cipta Media
timezone: Asia/Jakarta
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  juri-cme:
    title: Juri
    output: true
  hibahcme:
    title: Hibah CME
    output: true
  panitia:
    title: Panitia
    output: true
description: Arsip Cipta Media, menggunakan Jekyll dan github pages.
keywords: Cipta Media Seluler,CMS,blog,arsip,Jekyll,github,gh-pages
disqus:
  name: nama_disini
  public_key: public_key_disini
ga:
  id: UA-110953836-1
encoding: utf-8
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
baseurl: ""
defaults:
  -
    values:
      layout: "post"
include:
  - _redirects
