---
title: Cipta Media
timezone: Asia/Jakarta
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  juri-cme:
    title: Juri
    output: true
  hibahcme:
    title: Hibah CME
    output: true
  panitia:
    title: Panitia
    output: true
description: Halaman pembuka Cipta Media Ekspresi, Perayaan pengetahuan dan kreatifitas ekspresi perempuan dalam aneka ragam bentuk dan dinamikanya dengan rupa hibah dana tunai.
keywords: Seni, Budaya, Perempuan, Karya, Hibah, Ford Foundation
disqus:
  name: nama_disini
  public_key: public_key_disini
ga:
  id: UA-110953836-1
encoding: utf-8
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
baseurl: ""
defaults:
  -
    values:
      layout: "post"
include:
  - _redirects
